# Generated by Django 5.0.3 on 2024-04-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_video_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='video_id',
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(to='api.tag'),
        ),
    ]
