# Generated by Django 5.0.3 on 2024-12-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_video_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='advUrl',
            field=models.URLField(blank=True, help_text='Enter adv short link', null=True),
        ),
    ]
