# Generated by Django 5.0.3 on 2024-12-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_video_advurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='advUrl',
            field=models.URLField(blank=True, help_text='Enter adv short link', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='advUrl',
            field=models.URLField(blank=True, help_text='Enter adv short link', null=True),
        ),
    ]
