# Generated by Django 5.1.4 on 2024-12-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cartoon_advurl_category_advurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='IGCommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('likes', models.BigIntegerField(blank=True, default=0, null=True)),
                ('comments', models.BigIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
