# Generated by Django 5.1.4 on 2024-12-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_igcommerce_media_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='igcommerce',
            name='shortcode',
            field=models.CharField(default=123, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
